name: Update RSS
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update_rss:
    name: Update RSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load RSS
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://spearkkk.dev/rss
          count: 10 # default 5
      - name: Commmit
        run: |
            git config --global user.name 'spearkkk'
            git config --global user.email 'spearkkp@gmail.com'
            git add .
            git diff --quiet --cached || git commit -m "Update README"    
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
